# Generated by Django 5.1.5 on 2025-04-17 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la persona')),
                ('aval', models.CharField(max_length=100, verbose_name='Aval')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('domicilio', models.TextField(verbose_name='Domicilio')),
                ('ine', models.ImageField(blank=True, null=True, upload_to='ine/', verbose_name='INE')),
                ('trabajo', models.CharField(max_length=100, verbose_name='Trabajo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
