# Generated by Django 5.1.5 on 2025-04-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='curp',
            field=models.CharField(default='No proporcionado', max_length=100, verbose_name='CURP'),
        ),
    ]
