# Generated by Django 5.1.5 on 2025-07-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clave_elector',
            field=models.CharField(default='No proporcionado', max_length=100, verbose_name='Clave de elector'),
        ),
    ]
