# Generated by Django 5.1.5 on 2025-07-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_cliente_clave_elector'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clave_elector_aval',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de electro aval'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio_aval',
            field=models.TextField(blank=True, null=True, verbose_name='DomicilioAval'),
        ),
    ]
