# Generated by Django 5.1.5 on 2025-07-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_cliente_clave_elector_aval_cliente_domicilio_aval'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono_aval',
            field=models.TextField(blank=True, null=True, verbose_name='DomicilioAval'),
        ),
    ]
