# Generated by Django 5.1.5 on 2025-07-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_cliente_telefono_aval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clave_elector',
            field=models.CharField(blank=True, default='No proporcionado', max_length=100, null=True, verbose_name='Clave de elector'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio',
            field=models.TextField(blank=True, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_aval',
            field=models.TextField(blank=True, null=True, verbose_name='Domicilio Aval'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_aval',
            field=models.TextField(blank=True, null=True, verbose_name='Telefono aval'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='trabajo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trabajo'),
        ),
    ]
