# Generated by Django 5.1.5 on 2025-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_alter_cliente_clave_elector_alter_cliente_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, default='No proporcionado', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, default='No proporcionado', max_length=100, null=True, verbose_name='Municipio'),
        ),
    ]
