# Generated by Django 5.1.5 on 2025-08-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_cliente_estado_cliente_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aval2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aval'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='clave_elector_aval2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de electro aval'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio_aval2',
            field=models.TextField(blank=True, null=True, verbose_name='Domicilio Aval'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_aval2',
            field=models.TextField(blank=True, null=True, verbose_name='Telefono aval'),
        ),
    ]
