# Generated by Django 5.2.6 on 2026-04-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0010_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.comunidad', verbose_name='Comunidad'),
        ),
    ]
