# Generated by Django 5.2.6 on 2026-05-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_cliente_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_ahorro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
