# Generated by Django 5.2.6 on 2026-05-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_cliente_saldo_ahorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo_ahorro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
