# Generated by Django 5.2.1 on 2025-05-15 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0003_alter_cliente_id'),
        ('Prestamos', '0005_alter_prestamo_options_remove_prestamo_plazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_responsables', to='Clientes.cliente')),
            ],
            options={
                'verbose_name': 'Grupo de crédito',
                'verbose_name_plural': 'Grupos de crédito',
            },
        ),
        migrations.CreateModel(
            name='IntegranteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('es_representante', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='Grupos.grupo')),
            ],
            options={
                'unique_together': {('grupo', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='DetallePrestamoGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_pagos', models.IntegerField(verbose_name='Plazo en pagos')),
                ('prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prestamos.prestamo')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='Grupos.integrantegrupo')),
            ],
            options={
                'verbose_name': 'Detalle de préstamo grupal',
            },
        ),
    ]
