# Generated by Django 5.2.6 on 2025-09-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
