# Generated by Django 5.1.5 on 2025-06-05 15:52

import Gastos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_promotor', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[Gastos.models.validate_monto])),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('concepto', models.TextField()),
                ('fecha_modificado', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotores', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'fecha_registro'], name='Gastos_gast_usuario_9e0ac1_idx')],
            },
        ),
    ]
