# Generated by Django 5.2 on 2025-04-19 02:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de crédito/débito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro método')], max_length=50)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
