# Generated by Django 5.1.5 on 2025-07-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_pago_comentarios_pago_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_pago',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de pago'),
        ),
    ]
