# Generated by Django 5.2.6 on 2025-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0005_pago_cobrador_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
