# Generated by Django 5.2.6 on 2025-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0006_pago_fecha_programada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pago_parcial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='saldo_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
