# Generated by Django 5.2.6 on 2025-11-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0007_pago_pago_parcial_pago_saldo_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
