# Generated by Django 5.2.6 on 2025-12-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0008_pago_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='dias_transcurridos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
