# Generated by Django 5.2.6 on 2025-12-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0009_pago_dias_transcurridos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago parcial')], default='pendiente', max_length=10),
        ),
    ]
