# Generated by Django 5.2.6 on 2026-01-27 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0010_alter_pago_estado_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cobrador',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cobrador_asignado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='dias_transcurridos',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pago_parcial',
        ),
        migrations.AddField(
            model_name='pago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_programada',
            field=models.DateField(verbose_name='Fecha programada de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_pago',
            field=models.PositiveIntegerField(verbose_name='Número de cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='saldo_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cobrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='Pagos.pago')),
            ],
        ),
    ]
