# Generated by Django 5.2.6 on 2026-01-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0011_alter_pago_options_remove_pago_cobrador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cobrador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
