# Generated by Django 5.2.6 on 2026-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0012_pago_cobrador_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='ahorro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
