# Generated by Django 5.2.6 on 2026-05-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0013_abono_ahorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado'), ('AHORRO', 'Ahorro')], default='pendiente', max_length=10),
        ),
    ]
