# Generated by Django 5.2.6 on 2026-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0014_alter_pago_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('AHORRO', 'Ahorro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=10),
        ),
    ]
