# Generated by Django 5.0.4 on 2025-04-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0003_alter_prestamo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='aportacion_social',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de aportación social asociada al préstamo', max_digits=12, verbose_name='Aportación social'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='garantia_liquida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de garantía líquida requerida para el préstamo', max_digits=12, verbose_name='Garantía líquida'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='iva_sobre_intereses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA aplicado sobre los intereses del préstamo', max_digits=12, verbose_name='IVA sobre intereses'),
        ),
    ]
