# Generated by Django 5.0.4 on 2025-05-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0004_prestamo_aportacion_social_prestamo_garantia_liquida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='plazo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=10, verbose_name='Tipo de pago'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='total_pagos',
            field=models.IntegerField(default=0, help_text='Número total de pagos a realizar según el tipo seleccionado', verbose_name='Total de pagos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='aportacion_social',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aportación social'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='garantia_liquida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Garantía líquida'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='iva_sobre_intereses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA sobre intereses'),
        ),
    ]
