# Generated by Django 5.2.1 on 2025-05-15 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_alter_cliente_id'),
        ('Grupos', '0001_initial'),
        ('Prestamos', '0005_alter_prestamo_options_remove_prestamo_plazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='es_grupal',
            field=models.BooleanField(choices=[(False, 'Individual'), (True, 'Grupal')], default=False, verbose_name='Tipo de préstamo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='Grupos.grupo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='Clientes.cliente'),
        ),
    ]
