# Generated by Django 5.1.5 on 2025-07-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0006_prestamo_es_grupal_prestamo_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='archivo_firmado',
            field=models.FileField(blank=True, null=True, upload_to='Prestamos/firmados/', verbose_name='Archivo firmado'),
        ),
    ]
