# Generated by Django 5.1.5 on 2025-07-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0007_prestamo_archivo_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='informacion',
            field=models.FileField(blank=True, null=True, upload_to='Prestamos/pagares/', verbose_name='informacion'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='pagare',
            field=models.FileField(blank=True, null=True, upload_to='Prestamos/pagares/', verbose_name='Pagare'),
        ),
    ]
