# Generated by Django 5.1.5 on 2025-07-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0008_prestamo_informacion_prestamo_pagare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='informacion',
            field=models.FileField(blank=True, null=True, upload_to='Prestamos/informacions/', verbose_name='informacion'),
        ),
    ]
