# Generated by Django 5.2.6 on 2025-12-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0010_prestamo_promotor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='ahorro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ahorro por periodo'),
        ),
    ]
