# Generated by Django 5.2.6 on 2025-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0011_prestamo_ahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='folio',
            field=models.CharField(max_length=50, null=True, verbose_name='Folio de solicitud'),
        ),
    ]
