# Generated by Django 5.2.6 on 2026-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0012_prestamo_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='pago_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
